# Generated by Django 2.2.7 on 2019-11-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('codmat', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', help_text='Nome completo do aluno, com no máximo de 120 caracteres.', max_length=120, verbose_name='* Aluno:')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('coddis', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina', models.CharField(default='', help_text='Nome da disciplina, com no máximo 50 caracteres.', max_length=50, verbose_name='* Disciplina:')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('coddoc', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', help_text='Nome completo do professor/docente, com no máximo 120 caracteres.', max_length=120, verbose_name='* Nome do Professor: ')),
                ('end_cidade', models.CharField(default='', help_text='Nome da cidade do professor/docente, com no máximo 50 caracteres.', max_length=50, verbose_name='* Cidade: ')),
                ('end_bairro', models.CharField(default='', help_text='Nome do bairro do professor/docente, com no máximo 50 caracteres.', max_length=50, verbose_name='* Bairro: ')),
                ('end_rua', models.CharField(default='', help_text='Nome da rua do professor/docente, com no máximo 100 caracteres.', max_length=100, verbose_name='* Rua: ')),
                ('end_numero', models.CharField(default='', help_text='Número da moradia do professor/docente, com no máximo 10 caracteres.', max_length=10, verbose_name='* Número: ')),
                ('end_complemento', models.CharField(default='Sem complemento', help_text='Complemento da moradia do professor/docente, com no máximo 50 caracteres.', max_length=50, verbose_name='* Complemento: ')),
                ('telefone', models.CharField(default='(99) 99999-9999', help_text='Celular do professor/docente com máscara.', max_length=20, verbose_name='* Celular: ')),
                ('titulacao', models.CharField(default='', help_text='Titulo do professor/docente, com no máximo 50 caracteres.', max_length=50, verbose_name='* Titulação: ')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('faltas', models.IntegerField()),
                ('nota_final', models.FloatField()),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculdade.Discente')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculdade.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField()),
                ('carga', models.IntegerField()),
                ('horario', models.TimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculdade.Disciplina')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculdade.Docente')),
            ],
        ),
    ]
